name: FMM_TCS
channels:
- conda-forge
- dglteam/label/cu117
- nvidia
- pytorch
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_kmp_llvm
- absl-py=2.2.0=pyhd8ed1ab_0
- aiohttp=3.9.5=py310h2372a71_0
- aiosignal=1.3.1=pyhd8ed1ab_0
- alsa-lib=1.2.13=hb9d3cd8_0
- annotated-types=0.7.0=pyhd8ed1ab_1
- ants=2.5.1=h00ab1b0_0
- aom=3.9.1=hac33072_0
- appdirs=1.4.4=pyh9f0ad1d_0
- asttokens=2.4.1=pyhd8ed1ab_0
- async-timeout=4.0.3=pyhd8ed1ab_0
- attr=2.5.1=h166bdaf_1
- attrs=23.2.0=pyh71513ae_0
- aws-c-auth=0.8.1=h205f482_0
- aws-c-cal=0.8.1=h1a47875_3
- aws-c-common=0.10.6=hb9d3cd8_0
- aws-c-compression=0.3.0=h4e1184b_5
- aws-c-event-stream=0.5.0=h7959bf6_11
- aws-c-http=0.9.2=hefd7a92_4
- aws-c-io=0.15.3=h173a860_6
- aws-c-mqtt=0.11.0=h11f4f37_12
- aws-c-s3=0.7.9=he1b24dc_1
- aws-c-sdkutils=0.2.2=h4e1184b_0
- aws-checksums=0.2.2=h4e1184b_4
- aws-crt-cpp=0.29.9=he0e7f3f_2
- aws-sdk-cpp=1.11.489=h4d475cb_0
- azure-core-cpp=1.14.0=h5cfcd09_0
- azure-identity-cpp=1.10.0=h113e628_0
- azure-storage-blobs-cpp=12.13.0=h3cf044e_1
- azure-storage-common-cpp=12.8.0=h736e048_1
- azure-storage-files-datalake-cpp=12.12.0=ha633028_1
- blas=2.116=mkl
- blas-devel=3.9.0=16_linux64_mkl
- blosc=1.21.6=he440d0b_1
- brotli=1.1.0=hd590300_1
- brotli-bin=1.1.0=hd590300_1
- brotli-python=1.1.0=py310hc6cd4ac_1
- bzip2=1.0.8=hd590300_5
- c-ares=1.34.4=hb9d3cd8_0
- ca-certificates=2024.2.2=hbcca054_0
- cached-property=1.5.2=hd8ed1ab_1
- cached_property=1.5.2=pyha770c72_1
- cairo=1.18.4=h3394656_0
- certifi=2024.2.2=pyhd8ed1ab_0
- cftime=1.6.4=py310hf779ad0_2
- chardet=5.2.0=pyhd8ed1ab_3
- charset-normalizer=3.3.2=pyhd8ed1ab_0
- click=8.1.7=unix_pyh707e725_0
- colorama=0.4.6=pyhd8ed1ab_0
- comm=0.2.2=pyhd8ed1ab_0
- contourpy=1.2.1=py310hd41b1e2_0
- cuda-cudart=12.1.105=0
- cuda-cupti=12.1.105=0
- cuda-libraries=12.1.0=0
- cuda-nvrtc=12.1.105=0
- cuda-nvtx=12.1.105=0
- cuda-opencl=12.4.127=0
- cuda-runtime=12.1.0=0
- cudatoolkit=11.8.0=h4ba93d1_13
- cycler=0.12.1=pyhd8ed1ab_0
- cyrus-sasl=2.1.27=h54b06d7_7
- datasets=2.19.1=pyhd8ed1ab_0
- dav1d=1.2.1=hd590300_0
- dbus=1.13.6=h5008d03_3
- debugpy=1.8.1=py310hc6cd4ac_0
- decorator=5.1.1=pyhd8ed1ab_0
- dgl=1.0.2.cu117=py310_0
- dill=0.3.8=pyhd8ed1ab_0
- docker-pycreds=0.4.0=py_0
- eigen=3.4.0=h00ab1b0_0
- et_xmlfile=1.1.0=pyhd8ed1ab_0
- eval_type_backport=0.2.2=pyha770c72_0
- exceptiongroup=1.2.0=pyhd8ed1ab_2
- executing=2.0.1=pyhd8ed1ab_0
- expat=2.6.4=h5888daf_0
- faiss=1.9.0=py310cuda118hce52afa_0_cuda
- faiss-gpu=1.9.0=h418687c_0
- ffmpeg=7.1.1=gpl_h24e5c1d_701
- fftw=3.3.10=nompi_hf1063bd_110
- filelock=3.14.0=pyhd8ed1ab_0
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=h77eed37_2
- fontconfig=2.15.0=h7e30c49_1
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- fonttools=4.53.0=py310hc51659f_0
- freetype=2.12.1=h267a509_2
- freetype-py=2.3.0=pyhd8ed1ab_0
- fribidi=1.0.10=h36c2ea0_0
- frozenlist=1.4.1=py310h2372a71_0
- fsspec=2024.3.1=pyhca7485f_0
- gdk-pixbuf=2.42.12=hb9ae30d_0
- gettext=0.22.5=h59595ed_2
- gettext-tools=0.22.5=h59595ed_2
- gflags=2.2.2=he1b5a44_1004
- gitdb=4.0.11=pyhd8ed1ab_0
- gitpython=3.1.43=pyhd8ed1ab_0
- glib=2.82.2=h07242d1_1
- glib-tools=2.82.2=h4833e2c_1
- glog=0.7.1=hbabe93e_0
- gmp=6.3.0=h59595ed_1
- gmpy2=2.1.5=py310hc7909c9_1
- gnutls=3.7.9=hb077bed_0
- graphite2=1.3.13=h59595ed_1003
- greenlet=3.1.1=py310hf71b8c6_1
- grpcio=1.67.1=py310h56e06c5_2
- gst-plugins-base=1.24.7=h0a52356_0
- gstreamer=1.24.7=hf3bb09a_0
- h5netcdf=1.6.4=pyhd8ed1ab_0
- h5py=3.11.0=nompi_py310hf054cd7_102
- harfbuzz=10.4.0=h76408a6_0
- hdf4=4.2.15=h2a13503_7
- hdf5=1.14.3=nompi_hdf9ad27_105
- huggingface_hub=0.23.4=pyhd8ed1ab_0
- icu=75.1=he02047a_0
- idna=3.7=pyhd8ed1ab_0
- importlib-metadata=7.2.1=pyha770c72_0
- importlib_metadata=7.2.1=hd8ed1ab_0
- ipykernel=6.29.4=pyh3099207_0
- ipython=8.25.0=pyh707e725_0
- itk=5.3.0=py310hfdc917e_0
- jack=1.9.22=h7c63dc7_2
- jedi=0.19.1=pyhd8ed1ab_0
- jinja2=3.1.4=pyhd8ed1ab_0
- joblib=1.4.2=pyhd8ed1ab_0
- jupyter_client=8.6.2=pyhd8ed1ab_0
- jupyter_core=5.7.2=py310hff52083_0
- kernel-headers_linux-64=5.14.0=he073ed8_2
- keyutils=1.6.1=h166bdaf_0
- kiwisolver=1.4.5=py310hd41b1e2_1
- krb5=1.21.3=h659f571_0
- lame=3.100=h166bdaf_1003
- lazy-loader=0.4=pyhd8ed1ab_2
- lazy_loader=0.4=pyhd8ed1ab_2
- lcms2=2.16=hb7c19ff_0
- ld_impl_linux-64=2.40=h55db66e_0
- lerc=4.0.0=h27087fc_0
- level-zero=1.21.2=h84d6215_0
- libabseil=20240722.0=cxx17_hbbce691_4
- libaec=1.1.3=h59595ed_0
- libarrow=19.0.1=hfa2a6e7_0_cpu
- libarrow-acero=19.0.1=hcb10f89_0_cpu
- libarrow-dataset=19.0.1=hcb10f89_0_cpu
- libarrow-substrait=19.0.1=h08228c5_0_cpu
- libasprintf=0.22.5=h661eb56_2
- libasprintf-devel=0.22.5=h661eb56_2
- libass=0.17.3=hba53ac1_1
- libblas=3.9.0=16_linux64_mkl
- libboost=1.86.0=h6c02f8c_3
- libboost-python=1.86.0=py310ha2bacc8_3
- libbrotlicommon=1.1.0=hd590300_1
- libbrotlidec=1.1.0=hd590300_1
- libbrotlienc=1.1.0=hd590300_1
- libcap=2.71=h39aace5_0
- libcblas=3.9.0=16_linux64_mkl
- libclang-cpp15=15.0.7=default_h127d8a8_5
- libclang-cpp19.1=19.1.7=default_hb5137d0_1
- libclang13=19.1.7=default_h9c6a7e4_1
- libcrc32c=1.1.2=h9c3ff4c_0
- libcublas=12.1.0.26=0
- libcufft=11.0.2.4=0
- libcufile=1.9.1.3=0
- libcups=2.3.3=h4637d8d_4
- libcurand=10.3.5.147=0
- libcurl=8.12.1=h332b0f4_0
- libcusolver=11.4.4.55=0
- libcusparse=12.0.2.55=0
- libdb=6.2.32=h9c3ff4c_0
- libdeflate=1.20=hd590300_0
- libdrm=2.4.124=hb9d3cd8_0
- libedit=3.1.20191231=he28a2e2_2
- libegl=1.7.0=ha4b6fd6_2
- libev=4.33=hd590300_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.6.4=h5888daf_0
- libfaiss=1.9.0=cuda118hf323835_0_cuda
- libffi=3.4.2=h7f98852_5
- libflac=1.4.3=h59595ed_0
- libgcc=14.1.0=h77fa898_1
- libgcc-ng=14.1.0=h69a702a_1
- libgcrypt=1.10.3=hd590300_0
- libgcrypt-lib=1.11.0=hb9d3cd8_2
- libgettextpo=0.22.5=h59595ed_2
- libgettextpo-devel=0.22.5=h59595ed_2
- libgfortran-ng=13.2.0=h69a702a_7
- libgfortran5=13.2.0=hca663fb_7
- libgl=1.7.0=ha4b6fd6_2
- libglib=2.82.2=h2ff4ddf_1
- libglvnd=1.7.0=ha4b6fd6_2
- libglx=1.7.0=ha4b6fd6_2
- libgomp=14.1.0=h77fa898_1
- libgoogle-cloud=2.35.0=h2b5623c_0
- libgoogle-cloud-storage=2.35.0=h0121fbd_0
- libgpg-error=1.51=hbd13f7d_1
- libgrpc=1.67.1=h25350d4_2
- libhwloc=2.11.2=default_h0d58e46_1001
- libiconv=1.18=h4ce23a2_1
- libidn2=2.3.7=hd590300_0
- libitk=5.4.0=ha759891_2
- libjpeg-turbo=3.0.0=hd590300_1
- liblapack=3.9.0=16_linux64_mkl
- liblapacke=3.9.0=16_linux64_mkl
- libllvm15=15.0.7=ha7bfdaf_5
- libllvm18=18.1.8=hc9dba70_0
- libllvm19=19.1.7=ha7bfdaf_1
- liblzma=5.6.4=hb9d3cd8_0
- libnetcdf=4.9.2=nompi_h00e09a9_116
- libnghttp2=1.64.0=h161d5f1_0
- libnpp=12.0.2.50=0
- libnsl=2.0.1=hd590300_0
- libntlm=1.8=hb9d3cd8_0
- libnvjitlink=12.1.105=0
- libnvjpeg=12.1.1.14=0
- libogg=1.3.5=h4ab18f5_0
- libopentelemetry-cpp=1.18.0=hfcad708_1
- libopentelemetry-cpp-headers=1.18.0=ha770c72_1
- libopenvino=2025.0.0=hdc3f47d_1
- libopenvino-auto-batch-plugin=2025.0.0=h4d9b6c2_1
- libopenvino-auto-plugin=2025.0.0=h4d9b6c2_1
- libopenvino-hetero-plugin=2025.0.0=h981d57b_1
- libopenvino-intel-cpu-plugin=2025.0.0=hdc3f47d_1
- libopenvino-intel-gpu-plugin=2025.0.0=hdc3f47d_1
- libopenvino-intel-npu-plugin=2025.0.0=hdc3f47d_1
- libopenvino-ir-frontend=2025.0.0=h981d57b_1
- libopenvino-onnx-frontend=2025.0.0=h6363af5_1
- libopenvino-paddle-frontend=2025.0.0=h6363af5_1
- libopenvino-pytorch-frontend=2025.0.0=h5888daf_1
- libopenvino-tensorflow-frontend=2025.0.0=h630ec5c_1
- libopenvino-tensorflow-lite-frontend=2025.0.0=h5888daf_1
- libopus=1.3.1=h7f98852_1
- libparquet=19.0.1=h081d1f1_0_cpu
- libpciaccess=0.18=hd590300_0
- libpng=1.6.47=h943b412_0
- libpq=17.4=h27ae623_0
- libprotobuf=5.28.3=h6128344_1
- librdkit=2024.09.6=h84b0b3c_0
- libre2-11=2024.07.02=hbbce691_2
- librsvg=2.58.4=h49af25d_2
- libsndfile=1.2.2=hc60ed4a_1
- libsodium=1.0.18=h36c2ea0_1
- libsqlite=3.49.1=hee588c1_1
- libssh2=1.11.1=hf672d98_0
- libstdcxx=14.1.0=hc0a3c3a_1
- libstdcxx-ng=13.2.0=hc0a3c3a_7
- libsystemd0=257.3=h3dc2cb9_0
- libtasn1=4.19.0=h166bdaf_0
- libthrift=0.21.0=h0e7cc3e_0
- libtiff=4.6.0=h1dd3fc0_3
- libudev1=257.4=h9a4d06a_0
- libunistring=0.9.10=h7f98852_0
- libunwind=1.6.2=h9c3ff4c_0
- liburing=2.9=h84d6215_0
- libusb=1.0.27=hb9d3cd8_101
- libutf8proc=2.10.0=h4c51ac1_0
- libuuid=2.38.1=h0b41bf4_0
- libva=2.22.0=h4f16b4b_2
- libvorbis=1.3.7=h9c3ff4c_0
- libvpx=1.14.1=hac33072_0
- libwebp-base=1.4.0=hd590300_0
- libxcb=1.17.0=h8a09558_0
- libxcrypt=4.4.36=hd590300_1
- libxkbcommon=1.8.1=hc4a0caf_0
- libxml2=2.13.6=h8d12d68_0
- libzip=1.11.2=h6991a6a_0
- libzlib=1.3.1=h4ab18f5_1
- llvm-openmp=15.0.7=h0cdce71_0
- lz4-c=1.10.0=h5888daf_1
- markdown=3.6=pyhd8ed1ab_0
- markupsafe=2.1.5=py310h2372a71_0
- matplotlib=3.8.4=py310hff52083_2
- matplotlib-base=3.8.4=py310hef631a5_2
- matplotlib-inline=0.1.7=pyhd8ed1ab_0
- mkl=2022.1.0=h84fe81f_915
- mkl-devel=2022.1.0=ha770c72_916
- mkl-include=2022.1.0=h84fe81f_915
- mne-base=1.10.1=pyh694c41f_200
- mne-connectivity=0.7.0=pyhd8ed1ab_2
- mpc=1.3.1=hfe3b2da_0
- mpfr=4.2.1=h9458935_1
- mpg123=1.32.6=h59595ed_0
- mpmath=1.3.0=pyhd8ed1ab_0
- multidict=6.0.5=py310h2372a71_0
- multiprocess=0.70.16=py310h2372a71_0
- munkres=1.1.4=pyh9f0ad1d_0
- mysql-common=9.0.1=h266115a_4
- mysql-libs=9.0.1=he0572af_4
- ncurses=6.5=h59595ed_0
- nest-asyncio=1.6.0=pyhd8ed1ab_0
- netcdf4=1.7.2=nompi_py310h9f0ad05_101
- nettle=3.9.1=h7ab15ed_0
- networkx=3.3=pyhd8ed1ab_1
- nlohmann_json=3.11.3=he02047a_1
- nltk=3.9.1=pyhd8ed1ab_0
- nspr=4.36=h5888daf_0
- nss=3.108=h159eef7_0
- numpy=1.26.4=py310hb13e2d6_0
- ocl-icd=2.3.2=hd590300_1
- openh264=2.6.0=hc22cd8d_0
- openjpeg=2.5.2=h488ebb8_0
- openldap=2.6.9=he970967_0
- openpyxl=3.1.5=py310h0999ad4_1
- openssl=3.4.1=h7b32b05_0
- orc=2.0.3=h12ee42a_2
- p11-kit=0.24.1=hc5aa10d_0
- packaging=24.1=pyhd8ed1ab_0
- pandas=2.2.2=py310hf9f9076_1
- pango=1.56.2=h861ebed_0
- parso=0.8.4=pyhd8ed1ab_0
- pathtools=0.1.2=py_1
- pcre2=10.44=h0f59acf_0
- pexpect=4.9.0=pyhd8ed1ab_0
- pickleshare=0.7.5=py_1003
- pillow=10.4.0=py310he228d35_1
- pip=24.0=pyhd8ed1ab_0
- pixman=0.44.2=h29eaf8c_0
- platformdirs=4.2.2=pyhd8ed1ab_0
- ply=3.11=pyhd8ed1ab_2
- pooch=1.8.2=pyhd8ed1ab_3
- prometheus-cpp=1.3.0=ha5d0236_0
- prompt-toolkit=3.0.47=pyha770c72_0
- protobuf=5.28.3=py310hf71b8c6_0
- psutil=5.9.8=py310h2372a71_0
- pthread-stubs=0.4=h36c2ea0_1001
- ptyprocess=0.7.0=pyhd3deb0d_0
- pugixml=1.15=h3f63f65_0
- pulseaudio-client=17.0=hb77b528_0
- pure_eval=0.2.2=pyhd8ed1ab_0
- pyarrow=19.0.1=py310hff52083_0
- pyarrow-core=19.0.1=py310hac404ae_0_cpu
- pyarrow-hotfix=0.6=pyhd8ed1ab_0
- pycairo=1.27.0=py310h25ff670_0
- pydantic=2.9.2=pyhd8ed1ab_0
- pydantic-core=2.23.4=py310h505e2c1_0
- pydicom=2.4.4=pyhd8ed1ab_0
- pygments=2.18.0=pyhd8ed1ab_0
- pyparsing=3.1.2=pyhd8ed1ab_0
- pyqt=5.15.9=py310h04931ad_5
- pyqt5-sip=12.12.2=py310hc6cd4ac_5
- pysocks=1.7.1=pyha2e5f31_6
- python=3.10.14=hd12c33a_0_cpython
- python-dateutil=2.9.0=pyhd8ed1ab_0
- python-tzdata=2024.1=pyhd8ed1ab_0
- python-xxhash=3.4.1=py310h2372a71_0
- python_abi=3.10=4_cp310
- pytorch=2.3.0=py3.10_cuda12.1_cudnn8.9.2_0
- pytorch-cuda=12.1=ha16c6d3_5
- pytorch-mutex=1.0=cuda
- pytz=2024.1=pyhd8ed1ab_0
- pyyaml=6.0.1=py310h2372a71_1
- pyzmq=26.0.3=py310h6883aea_0
- qt-main=5.15.15=hc3cb62f_2
- rdkit=2024.09.6=py310hcd13295_0
- re2=2024.07.02=h9925aae_2
- readline=8.2=h8228510_1
- regex=2024.5.15=py310hc51659f_0
- reportlab=4.3.1=py310ha75aee5_0
- requests=2.31.0=pyhd8ed1ab_0
- rlpycairo=0.2.0=pyhd8ed1ab_0
- ruamel_yaml=0.15.80=py310h2372a71_1009
- s2n=1.5.11=h072c03f_0
- safetensors=0.4.3=py310hcb5633a_0
- scikit-learn=1.7.1=py310h228f341_0
- scipy=1.14.0=py310h3fe0a75_2
- sdl2=2.32.50=h9b8e6db_1
- sdl3=3.2.8=h3083f51_0
- sentry-sdk=2.1.1=pyhd8ed1ab_0
- setproctitle=1.3.3=py310h2372a71_0
- setuptools=69.5.1=pyhd8ed1ab_0
- sip=6.7.12=py310hc6cd4ac_0
- six=1.16.0=pyh6c4a22f_0
- smmap=5.0.0=pyhd8ed1ab_0
- snappy=1.2.1=h8bd8927_1
- sqlalchemy=2.0.39=py310ha75aee5_1
- stack_data=0.6.2=pyhd8ed1ab_0
- svt-av1=3.0.1=h5888daf_0
- sympy=1.12=pypyh9d50eac_103
- sysroot_linux-64=2.34=h087de78_2
- tbb=2021.13.0=hceb3a55_1
- tensorboard=2.19.0=pyhd8ed1ab_0
- tensorboard-data-server=0.7.0=py310h6c63255_2
- threadpoolctl=3.6.0=pyhecae5ae_0
- tk=8.6.13=noxft_h4845f30_101
- tokenizers=0.19.1=py310h320607d_0
- toml=0.10.2=pyhd8ed1ab_0
- tomli=2.0.1=pyhd8ed1ab_0
- torchaudio=2.3.0=py310_cu121
- torchtriton=2.3.0=py310
- torchvision=0.18.0=py310_cu121
- tornado=6.4.1=py310hc51659f_0
- tqdm=4.66.4=pyhd8ed1ab_0
- traitlets=5.14.3=pyhd8ed1ab_0
- transformers=4.42.3=pyhd8ed1ab_0
- typing=3.10.0.0=pyhd8ed1ab_2
- typing-extensions=4.11.0=hd8ed1ab_0
- typing_extensions=4.11.0=pyha770c72_0
- tzdata=2024a=h0c530f3_0
- unicodedata2=15.1.0=py310h2372a71_0
- urllib3=2.2.1=pyhd8ed1ab_0
- wandb=0.19.8=py310h69e60fc_0
- wayland=1.23.1=h3e06ad9_0
- wayland-protocols=1.36=hd8ed1ab_0
- wcwidth=0.2.13=pyhd8ed1ab_0
- werkzeug=3.1.3=pyhd8ed1ab_1
- wheel=0.43.0=pyhd8ed1ab_1
- x264=1!164.3095=h166bdaf_2
- x265=3.5=h924138e_3
- xarray=2025.6.1=pyhd8ed1ab_1
- xcb-util=0.4.1=hb711507_2
- xcb-util-image=0.4.0=hb711507_2
- xcb-util-keysyms=0.4.1=hb711507_0
- xcb-util-renderutil=0.3.10=hb711507_0
- xcb-util-wm=0.4.2=hb711507_0
- xkeyboard-config=2.42=h4ab18f5_0
- xorg-fixesproto=5.0=h7f98852_1002
- xorg-kbproto=1.0.7=h7f98852_1002
- xorg-libice=1.1.2=hb9d3cd8_0
- xorg-libsm=1.2.5=he73a12e_0
- xorg-libx11=1.8.11=h4f16b4b_0
- xorg-libxau=1.0.12=hb9d3cd8_0
- xorg-libxcursor=1.2.3=hb9d3cd8_0
- xorg-libxdamage=1.1.6=hb9d3cd8_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- xorg-libxext=1.3.6=hb9d3cd8_0
- xorg-libxfixes=6.0.1=hb9d3cd8_0
- xorg-libxrender=0.9.12=hb9d3cd8_0
- xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
- xorg-libxxf86vm=1.1.6=hb9d3cd8_0
- xorg-renderproto=0.11.1=h7f98852_1002
- xorg-xextproto=7.3.0=h0b41bf4_1003
- xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
- xorg-xproto=7.0.31=h7f98852_1007
- xxhash=0.8.2=hd590300_0
- xz=5.2.6=h166bdaf_0
- yaml=0.2.5=h7f98852_2
- yarl=1.9.4=py310h2372a71_0
- zeromq=4.3.5=h75354e8_4
- zipp=3.19.2=pyhd8ed1ab_0
- zlib=1.3.1=h4ab18f5_1
- zstd=1.5.6=ha6fb4c9_0